### ISSUE TITLE
Feature Request: Option to return feature vectors

### ISSUE THREAD

**Issue by iracooke** [Legana/ampir#10]
At present it isn't possible to access the feature vectors calculated with "calculate_features" in any of the user-facing functions. 

I suggest a couple of possible options;

1. Expose 'calculate_features'
2. Provide an option to 'predict_amps' to add all the feature columns into the table that is returned to the user.

**Comment by Legana** [comment]
I will export `calculate_features`. That way it is easier to access for users for e.g. when they want to make their own model too.

**Comment by iracooke** [comment]
@Legana please link to the commit with code changes when you close the issue

**Comment by Legana** [comment]
https://github.com/Legana/ampir/commit/ebc18ec328ac25894f47a652f50775c258672b78
