### ISSUE TITLE
ampir fails when input sequences contain stop codons

### ISSUE THREAD

**Issue by iracooke** [Legana/ampir#13]
I tried with the following code

```r
library(ampir)


test_data <- data.frame(name = c("withstop","nostop"),
                        seq=c("DKLIGSCVWGAVNYTSDCNGECKRRGYKGGHCGSFANVNCWCET*",
                          "DKLIGSCVWGAVNYTSDCNGECKRRGYKGGHCGSFANVNCWCET"),
                        stringsAsFactors = FALSE)


predict_amps(test_data)
```

This produces the following output

> Could not run prediction for 1 proteins because they were either too short or contained invalid amino acids

|name     |seq                                           |  prob_AMP|
|:--------|:---------------------------------------------|---------:|
|withstop |DKLIGSCVWGAVNYTSDCNGECKRRGYKGGHCGSFANVNCWCET* |        NA|
|nostop   |DKLIGSCVWGAVNYTSDCNGECKRRGYKGGHCGSFANVNCWCET  | 0.6618123|

I believe that the correct behaviour here would be to silently remove the terminal stop codon so that prediction will work properly

**Comment by Legana** [comment]
Fixed with 34860d7ef2ffe5cd803363d3eae13f51dee8210d
