### ISSUE TITLE
Improve behaviour when input sequences are provided as a factor

### ISSUE THREAD

**Issue by iracooke** [Legana/ampir#14]
The following code

```r
library(ampir)


test_data <- data.frame(name = c("seq1","seq2"),
                        seq=c("DKLIGSCVWGAVNYTSDCNGECKRRGYKGGHCGSFANVNCWCET",
                              "QRVRNPQSCRWNMGVCIPFLCRVGMRQIGTCFGPRVPCCRR"))


predict_amps(test_data)
```

Produces a difficult to interpret error

> Error in nchar(faa_df[, 2]) : 'nchar()' requires a character vector

ampir requires that the second column of input is a character vector but fails if it is a factor.  I see a couple of potential options for a fix

1. Check if a factor is provided and stop with a more helpful error message
2. Automatically convert factor to character vector

**Comment by Legana** [comment]
commit b90940385e9bcb32b3dfb0e49918ad1f56a23ea9 now includes code that stops and provides a helpful error message if the input is not in character format
