### ISSUE TITLE
Question about accuracy of prediction

### ISSUE THREAD

**Issue by flystar233** [Legana/ampir#21]
Hi，Legana
I have read your project code and related design process (AMP_pub) and I'm very admired for your detailed work. But there is some questions about the accuracy of AMP prediction.
The test data I used was downloaded from the APD3 database (min_len 10, rmdup seq).The figure below is the data density map generated by ggplot2.
![image](https://user-images.githubusercontent.com/20431495/98067465-8dec5180-1e94-11eb-90b0-407612afff20.png)
It can be seen from the figure that a large amount of data is marked as non-AMP.
AMP test data:  [amp_rmdup_min10.zip](https://github.com/Legana/ampir/files/5485409/amp_rmdup_min10.zip)

By the way, The figure below is the data density map generated by ggplot2.(The result is predicted by amPEP.py)
Article : amPEPpy 1.0: A portable and accurate antimicrobial peptide prediction tool
![image](https://user-images.githubusercontent.com/20431495/98067678-1539c500-1e95-11eb-9abf-89412eee1dcf.png)

I don’t know if it is the difference between support vector machine and random forest or the difference in the calculation method of amino acid features.
Waiting for your reply, Thanks.

**Comment by iracooke** [comment]
Dear @flystar233 

For these databases it's important to select the mature peptide model.  For this you would need to run `predict_amps` with option `model = "mature"`

It would be interesting to see if this resolves the discrepancy.

**Comment by flystar233** [comment]
Yes!  get better result. Thanks.
![image](https://user-images.githubusercontent.com/20431495/98076844-06a9d880-1eaa-11eb-94e0-1451aabed379.png)

**Comment by iracooke** [comment]
@flystar233 Great.  That makes sense now. ampir is unusual because our default model is based on precursor proteins (for genome scans).  Most other predictors are based on mature peptides. The `model` parameter allows switching between these modes
